name: "Hijack"
description: "Share something in a place where no one knows me."

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-sass-converter
paginate: 10
paginate_path: /page-:num
theme: null

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: compressed
    sass_dir: assets/css/

collections_dir: my_collections
collections:
  microposts:
    output: true

timezone: Asia/Shanghai

author: getupbuzz