name: "Hijack"
description: "Share something in a place where no one knows me."

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: route

plugins:
  - jekyll-paginate
  - jekyll-feed
paginate: 10
paginate_path: /page-:num

gems:
  - jekyll-sitemap

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

